### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by robinandeer**
What do you think @ingkebil?

----
Message for potential merge into canonical repo:

> I'm sorry; we can't have an official Clinical fork without a logo.

> I think it say something about it in our AMSystems. I would dig it out but, you know, it's AMSystems, so I ask you take my word for it instead :wink:

### CODE REVIEW

**Comment by robinandeer** [comment]
Apparently you also need to touch the docs according to contributing guidelines so I've added the logo there as well.

As a bonus I included the dev dependencies in a separate ``requirements-dev.txt`` pip file.

**Comment by ingkebil** [comment]
I'm sure it's in a previous version of our software development guidelines on AMSystems. Please do look this up ;)

I'm not so fond of base colour designs, but that's no reason to vote against this. I can get used to this.

**Comment by robinandeer** [comment]
Since I'm going for DNA base colors, what choice do I have, hehe :sweat_smile:

**Comment by robinandeer** [comment]
I'll merge this then and will add some more explicit sarcasm to the AMSystems comment...

**Pull request merged**
